# Generated by Django 3.0.2 on 2020-02-01 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('note_text', models.TextField(max_length=300, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('item_text', models.TextField(max_length=300, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Todo')),
            ],
        ),
    ]
