# Generated by Django 3.0.2 on 2020-01-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20200131_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
